### ISSUE TITLE
Auto complete using completing read and a sql query on current column.

### ISSUE THREAD

**Issue by olymk2** [xenodium/sqlite-mode-extras#1]
I sent you some code to add auto complete curious if you would be interested in a PR I am thinking it could be made a flag that people can set to enable as I imagine on super large table's there could be performance issues.

Thought I would see what your thoughts are ?

**Comment by xenodium** [comment]
Hiya Oliver. Sorry about that, I seem to have slipped this through the cracks. Was this over email? mastodon? Want to share the snippets here?

**Comment by olymk2** [comment]
it was on mastodon, I am happy to create a PR for it ?

**Comment by xenodium** [comment]
Oh, found it https://indieweb.social/@xenodium/111959782387767609 Sorry about that.

> it was on mastodon, I am happy to create a PR for it ?

Yup. It's a nice feature.

> I am thinking it could be made a flag that people can set to enable

Sounds good. We can enable by default so it's more discoverable. Folks can optionally disable it.

**Comment by olymk2** [comment]
https://github.com/xenodium/sqlite-mode-extras/pull/2 One thought I had is instead of the toggle it could be the sql itself, so nil disable else treat it as a sql query this way users could override it if required, not sure how useful that would be ?

**Comment by xenodium** [comment]
> https://github.com/xenodium/sqlite-mode-extras/pull/2 One thought I had is instead of the toggle it could be the sql itself, > so nil disable else treat it as a sql query this way users could override it if required, not sure how useful that would be ?

Maybe skip this one for now and revisit if we find a need for it?

**Comment by olymk2** [comment]
> > #2 One thought I had is instead of the toggle it could be the sql itself, > so nil disable else treat it as a sql query this way users could override it if required, not sure how useful that would be ?
> 
> Maybe skip this one for now and revisit if we find a need for it?

Fine by me I recon most sqlite databases are small enough, its only if you have a very large table with lot of variation on some of the columns then the group by could cause a full scan, where as just selecting the top 100 would likely be quicker.

**Comment by xenodium** [comment]
We can always revisit. Let's wait a little and gather user feedback.

Will close this issue since we've now merged the changes for the initial intent.
